### ISSUE TITLE
Fails to build with Boost 1.70 (Beta1)

### ISSUE THREAD

**Issue by jbeich** [MusicPlayerDaemon/ncmpc#49]
Regressed by boostorg/asio@a72fbb0b867f:
```c++
In file included from ../src/player_command.cxx:23:
../src/mpdclient.hxx:133:27: error: no member named 'get_io_service' in
      'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock,
      boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                return enter_idle_timer.get_io_service();
                       ~~~~~~~~~~~~~~~~ ^
../src/mpdclient.hxx:132:8: error: cannot deduce return type 'auto &' for function with no return statements
        auto &get_io_service() noexcept {
              ^
2 errors generated.
```

**Comment by jbeich** [comment]
Still fails:
```c++
../src/LyricsPage.cxx:78:25: error: no member named 'get_io_service' in
      'boost::asio::basic_waitable_timer<std::__1::chrono::steady_clock,
      boost::asio::wait_traits<std::__1::chrono::steady_clock>, boost::asio::executor>'
                return loader_timeout.get_io_service();
                       ~~~~~~~~~~~~~~ ^
../src/LyricsPage.cxx:77:8: error: cannot deduce return type 'auto &' for function with no return statements
        auto &get_io_service() noexcept {
              ^
```

**Comment by MaxKellermann** [comment]
True, my Boost test build had the lyrics screen disabled.

4f767b38e527ee855cf7583aa5a67b59189ddbea
